# Generated by Django 3.1.4 on 2020-12-20 07:58

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20, verbose_name='货币类型')),
                ('amount', models.BigIntegerField(verbose_name='保函金额')),
                ('type', models.CharField(max_length=10, verbose_name='保函类型')),
                ('serial_number', models.CharField(max_length=50, verbose_name='保函编号')),
                ('type_of_issuing_institution', models.CharField(max_length=15, verbose_name='开立机构')),
                ('issuing_bank', models.CharField(max_length=50, verbose_name='开立行')),
                ('date_of_issuing', models.DateField(verbose_name='开立日期')),
                ('condition_of_coming_into_effectiveness', models.CharField(max_length=20, verbose_name='生效条件')),
                ('date_of_coming_into_effectiveness', models.DateField(verbose_name='生效日期')),
                ('expiring_date', models.DateField(verbose_name='到期日')),
                ('following_up_serial_number', models.CharField(max_length=50, verbose_name='接续保函编号')),
                ('is_returned', models.BooleanField(verbose_name='是否已退还给供应商')),
                ('remark', models.TextField(default='无', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '保函信息',
                'verbose_name_plural': '保函信息',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_order_number', models.CharField(max_length=20, verbose_name='合同号简写')),
                ('person_in_charge', models.CharField(blank=True, max_length=10, null=True, verbose_name='合同负责人')),
                ('client_type', models.CharField(max_length=20, verbose_name='客户类型')),
                ('country_of_origin', models.CharField(max_length=20, verbose_name='原产地')),
                ('chinese_name_of_equipment', models.CharField(blank=True, max_length=30, null=True, verbose_name='设备名称(中文)')),
                ('english_name_of_equipment', models.CharField(blank=True, max_length=30, null=True, verbose_name='设备名称(英文)')),
                ('project_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='业主项目号')),
                ('po_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='PO号')),
                ('mr_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='MR号')),
                ('currency_of_po', models.CharField(max_length=20, verbose_name='PO的货币类型')),
                ('amount_of_po', models.BigIntegerField(verbose_name='PO金额')),
                ('currency_of_chinese_order', models.CharField(blank=True, max_length=20, null=True, verbose_name='中文合同的货币类型')),
                ('amount_of_chinese_order', models.BigIntegerField(blank=True, null=True, verbose_name='中文合同的金额')),
                ('currency_of_freight', models.CharField(blank=True, max_length=20, null=True, verbose_name='运费的货币类型')),
                ('amount_of_freight', models.CharField(blank=True, max_length=20, null=True, verbose_name='运费金额')),
                ('apg_is_needed', models.CharField(max_length=20, verbose_name='是否需要开预付款保函')),
                ('pg_is_needed', models.CharField(max_length=20, verbose_name='是否需要开履约保函')),
                ('condition_of_coming_into_effectiveness', models.CharField(blank=True, max_length=20, null=True, verbose_name='合同生效条件')),
                ('guarantee_period', models.BigIntegerField(blank=True, null=True, verbose_name='质保期(月)')),
                ('date_of_sending_order_to_vendor', models.DateField(blank=True, null=True, verbose_name='PO发给供应商的日期')),
                ('po_signing_date', models.DateField(blank=True, null=True, verbose_name='PO签字日期')),
                ('is_canceled', models.BooleanField(verbose_name='合同是否已取消')),
                ('is_transferred_to_r', models.BooleanField(verbose_name='是否已转让给瑞程')),
                ('date_of_coming_into_effectiveness', models.DateField(blank=True, null=True, verbose_name='合同生效日期')),
                ('comment_for_first_party', models.TextField(blank=True, null=True, verbose_name='给业主/分包商看的注释')),
                ('remark', models.TextField(default='无', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '合同信息',
                'verbose_name_plural': '合同信息',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='中文简称')),
                ('chinese_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文全称')),
                ('english_short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='英文简称')),
                ('english_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文全称')),
                ('chinese_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文地址')),
                ('english_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文地址')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(default='无', max_length=500, verbose_name='备注')),
            ],
            options={
                'verbose_name': '供应商信息',
                'verbose_name_plural': '供应商信息',
            },
        ),
        migrations.CreateModel(
            name='OrderToGuarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_of_guarantee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.guarantee', verbose_name='保函编号')),
                ('short_order_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.order', verbose_name='合同号简写')),
            ],
            options={
                'verbose_name': '合同保函中间表',
                'verbose_name_plural': '合同保函中间表',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.vendor'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='short_order_number',
            field=models.ManyToManyField(through='general.OrderToGuarantee', to='general.Order', verbose_name='合同号简写'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='部门')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='职务')),
                ('landline', models.CharField(blank=True, max_length=20, null=True, verbose_name='座机号')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱')),
                ('qq', models.CharField(blank=True, max_length=20, null=True)),
                ('wechat', models.CharField(blank=True, max_length=25, null=True, verbose_name='微信')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('remark', models.TextField(default='无', max_length=500, verbose_name='备注')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.vendor')),
            ],
            options={
                'verbose_name': '供应商联系人信息',
                'verbose_name_plural': '供应商联系人信息',
            },
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.BigIntegerField(blank=True, null=True, verbose_name='手机号')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '网站用户信息',
                'verbose_name_plural': '网站用户信息',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
