# Generated by Django 3.1.4 on 2020-12-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(max_length=20, null=True, verbose_name='部门'),
        ),
    ]
