# Generated by Django 3.1.4 on 2020-12-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20201216_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '合同信息', 'verbose_name_plural': '合同信息'},
        ),
        migrations.AlterModelOptions(
            name='ordertoguarantee',
            options={'verbose_name': '合同保函中间表', 'verbose_name_plural': '合同保函中间表'},
        ),
        migrations.AlterModelOptions(
            name='userinformation',
            options={'verbose_name': '网站用户信息', 'verbose_name_plural': '网站用户信息'},
        ),
    ]
