# Generated by Django 3.1.4 on 2020-12-20 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20201220_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContact',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('department', models.CharField(max_length=20, null=True, verbose_name='部门')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='职务')),
                ('landline', models.CharField(blank=True, max_length=20, null=True, verbose_name='座机号')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='邮箱')),
                ('qq', models.CharField(blank=True, max_length=20, null=True)),
                ('wechat', models.CharField(blank=True, max_length=25, null=True, verbose_name='微信')),
                ('created_time', models.DateTimeField(blank=True, editable=False)),
                ('updated_time', models.DateTimeField(blank=True, editable=False)),
                ('remark', models.TextField(default='无', max_length=500, verbose_name='备注')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='general.vendor')),
            ],
            options={
                'verbose_name': 'historical 供应商联系人信息',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
