# Generated by Django 3.1.4 on 2020-12-16 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20201216_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guarantee',
            options={'verbose_name': '保函信息', 'verbose_name_plural': '保函信息'},
        ),
    ]
